spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geek_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

application:
  jwt:
    secretKey: 294A404E635166546A576E5A7234753778214125442A472D4B6150645367556B
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 10

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"