spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geek_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #mail sender
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      botunigroup@gmail.com
    password:
      eyohprroirncbcqg
    protocol:
      smtp
    properties:
      mail:
        smtp:
          auth:
            true
          connectiontimeout:
            5000
          timeout:
            3000
          writetimeout:
            5000
upload:
  name: uploads

application:
  jwt:
    secretKey: 294A404E635166546A576E5A7234753778214125442A472D4B6150645367556B
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
  database:
    url: jdbc:postgresql://localhost:5432/geek_hub
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    max-pool-size: 5