version: '3.9'

services:
  postgres:
    container_name: spring-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: coursework
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped