version: '3.9'

services:
  postgres:
    container_name: spring-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: geek_hub
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/geek_hub
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5080:80"
    restart: unless-stopped
    networks:
      - postgres
    depends_on:
      - my-app

networks:
  postgres:
    driver: bridge